version: '3'
services:
  app:
    build: .
    container_name: event-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/events
      - NODE_ENV=development
      - PORT=8383
      - CONSUL_URL=consul.fireup.studio
    ports:
      - "8383:8383"
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node ./src/server.js"

  db:
    image: postgres:13-alpine
    container_name: postgres-db-events
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events

    volumes:
      - postgres-data-events:/var/lib/postgresql/data
volumes:
  postgres-data-events:
