### FETCH all events
GET http://localhost:8383/api/v1/info/all

### FETCH all events which still have free capacity
GET http://localhost:8383/api/v1/info/available

### FETCH one event
GET http://localhost:8383/api/v1/info/1

### FETCH event validated tickets
GET http://localhost:8383/api/v1/info/1/validatedCount

### FETCH capacity of event
GET http://localhost:8383/api/v1/info/1/capacity

### FETCH capacity of all events
GET http://localhost:8383/api/v1/info/all/available

### Create a new event
POST http://localhost:8383/api/v1
Content-Type: application/json

{
  "name": "Test name",
  "dateOf": "2024-06-10T12:00:00.000Z",
  "location": "Prague",
  "capacity": 100,
  "userId": 42
}

### Update an event
PUT http://localhost:8383/api/v1/1
Content-Type: application/json

{
  "name": "Test name"
}

### Delete event
DELETE http://localhost:8383/api/v1/1

### Health check
GET http://localhost:8383/health

